FROM python:3.7

WORKDIR /app

COPY Pipfile .
COPY Pipfile.lock .

RUN pip install --upgrade pip && \
    pip install pipenv && \
    pipenv install --dev --system --deploy --ignore-pipfile

COPY . .

# WORKDIR /app/src

ENV PYTHONDONTWRITEBYTECODE 1

CMD flask run --host=0.0.0.0