FROM python:3.8

# Install dependencies
RUN pip install --upgrade pip \
    && pip install pipenv

WORKDIR /app

# Dependency Management copy for cache
COPY Pipfile .
COPY Pipfile.lock .

# Install dependencies with pipenv
RUN pipenv install --dev --system --deploy --ignore-pipfile

COPY . .

EXPOSE 5000

# Run Flask server
CMD flask run --host=0.0.0.0